spring:
  redis:
    host: 120.26.251.45
    port: 6379
    timeout: 6000
    password: Chen1005&*()
  datasource:
    username: root
    password: Chen1005
    url: jdbc:mysql://120.26.251.45:3306/codebarry_web?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver